// <auto-generated />
using System;
using GymBro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace GymBro.Infrastructure.Migrations
{
    [DbContext(typeof(GymBroDbContext))]
    [Migration("20260826174946_ConsolidacionFinalV2Dominio")]
    partial class ConsolidacionFinalV2Dominio
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymBro.Domain.Entities.DosificacionVolumetrica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("ParteCuerpo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("parte_cuerpo");

                    b.Property<int>("RepeticionesMaximas")
                        .HasColumnType("integer")
                        .HasColumnName("repeticiones_maximas");

                    b.Property<int>("RepeticionesMinimas")
                        .HasColumnType("integer")
                        .HasColumnName("repeticiones_minimas");

                    b.Property<int>("SeriesMaximas")
                        .HasColumnType("integer")
                        .HasColumnName("series_maximas");

                    b.Property<int>("SeriesMinimas")
                        .HasColumnType("integer")
                        .HasColumnName("series_minimas");

                    b.Property<string>("SubzonaObjetivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("subzona_objetivo");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_alta");

                    b.Property<int?>("UsuarioBaja")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_baja");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("ZonaObjetivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zona_objetivo");

                    b.HasKey("Id")
                        .HasName("pk_dosificaciones");

                    b.ToTable("dosificaciones", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("Dificultad")
                        .HasColumnType("integer")
                        .HasColumnName("dificultad");

                    b.Property<string>("Ejecucion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("ejecucion");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector")
                        .HasColumnName("embedding");

                    b.Property<string>("Equipamiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipamiento");

                    b.Property<string>("Estabilizadores")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("estabilizadores");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("MusculoPrincipal")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("musculo_principal");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Preparacion")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("preparacion");

                    b.Property<string>("Sinergistas")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sinergistas");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_alta");

                    b.Property<int?>("UsuarioBaja")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_baja");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modificacion");

                    b.Property<string>("ZonaObjetivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("zona_objetivo");

                    b.HasKey("Id")
                        .HasName("pk_ejercicios");

                    b.ToTable("ejercicios", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.MatrizRecomendacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer")
                        .HasColumnName("id");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<bool>("AplicaDiabetes")
                        .HasColumnType("boolean")
                        .HasColumnName("aplica_diabetes");

                    b.Property<bool>("AplicaHipertension")
                        .HasColumnType("boolean")
                        .HasColumnName("aplica_hipertension");

                    b.Property<string>("CategoriaIMC")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria_imc");

                    b.Property<string>("CategoriaRutina")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("categoria_rutina");

                    b.Property<int>("Edad")
                        .HasColumnType("integer")
                        .HasColumnName("edad");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("genero");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objetivo");

                    b.Property<string>("RecomendacionGeneral")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("recomendacion_general");

                    b.Property<string>("SugerenciaDieta")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("sugerencia_dieta");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_alta");

                    b.Property<int?>("UsuarioBaja")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_baja");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id")
                        .HasName("pk_matrices_recomendacion");

                    b.ToTable("matrices_recomendacion", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.MedicionFisica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AlturaCm")
                        .HasColumnType("numeric")
                        .HasColumnName("altura_cm");

                    b.Property<string>("CondicionMedica")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("condicion_medica");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("FrecuenciaCardiacaReposo")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_cardiaca_reposo");

                    b.Property<int>("FrecuenciaEntrenamientoDias")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_entrenamiento_dias");

                    b.Property<decimal>("HorasSuenoUltimaNoche")
                        .HasColumnType("numeric")
                        .HasColumnName("horas_sueno_ultima_noche");

                    b.Property<decimal>("IMC")
                        .HasColumnType("numeric")
                        .HasColumnName("imc");

                    b.Property<decimal>("IngestaAguaLitros")
                        .HasColumnType("numeric")
                        .HasColumnName("ingesta_agua_litros");

                    b.Property<int>("NivelEstres")
                        .HasColumnType("integer")
                        .HasColumnName("nivel_estres");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_kg");

                    b.Property<decimal>("PorcentajeGrasa")
                        .HasColumnType("numeric")
                        .HasColumnName("porcentaje_grasa");

                    b.Property<decimal>("PresionArterialDiastolica")
                        .HasColumnType("numeric")
                        .HasColumnName("presion_arterial_diastolica");

                    b.Property<decimal>("PresionArterialMedia")
                        .HasColumnType("numeric")
                        .HasColumnName("presion_arterial_media");

                    b.Property<decimal>("PresionArterialSistolica")
                        .HasColumnType("numeric")
                        .HasColumnName("presion_arterial_sistolica");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("socio_id");

                    b.Property<string>("TipoEntrenamiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("tipo_entrenamiento");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_alta");

                    b.Property<int?>("UsuarioBaja")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_baja");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id")
                        .HasName("pk_mediciones_fisicas");

                    b.HasIndex("SocioId")
                        .HasDatabaseName("ix_mediciones_fisicas_socio_id");

                    b.ToTable("mediciones_fisicas", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.SesionEjercicio", b =>
                {
                    b.Property<Guid>("SesionId")
                        .HasColumnType("uuid")
                        .HasColumnName("sesion_id");

                    b.Property<Guid>("EjercicioId")
                        .HasColumnType("uuid")
                        .HasColumnName("ejercicio_id");

                    b.Property<decimal>("PesoLevantadoKg")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_levantado_kg");

                    b.Property<int>("Repeticiones")
                        .HasColumnType("integer")
                        .HasColumnName("repeticiones");

                    b.Property<int>("Series")
                        .HasColumnType("integer")
                        .HasColumnName("series");

                    b.Property<int>("TiempoDescansoSegundos")
                        .HasColumnType("integer")
                        .HasColumnName("tiempo_descanso_segundos");

                    b.HasKey("SesionId", "EjercicioId")
                        .HasName("pk_sesiones_ejercicios");

                    b.HasIndex("EjercicioId")
                        .HasDatabaseName("ix_sesiones_ejercicios_ejercicio_id");

                    b.ToTable("sesiones_ejercicios", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("CaloriasQuemadas")
                        .HasColumnType("integer")
                        .HasColumnName("calorias_quemadas");

                    b.Property<int>("DuracionMinutos")
                        .HasColumnType("integer")
                        .HasColumnName("duracion_minutos");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<int>("FrecuenciaCardiacaMaxima")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_cardiaca_maxima");

                    b.Property<int>("FrecuenciaCardiacaPromedio")
                        .HasColumnType("integer")
                        .HasColumnName("frecuencia_cardiaca_promedio");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("socio_id");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_alta");

                    b.Property<int?>("UsuarioBaja")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_baja");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id")
                        .HasName("pk_sesiones");

                    b.HasIndex("SocioId")
                        .HasDatabaseName("ix_sesiones_socio_id");

                    b.ToTable("sesiones", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.Socio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<DateTime>("FechaNacimiento")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_nacimiento");

                    b.Property<string>("Genero")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("genero");

                    b.Property<string>("Nivel")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nivel");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<string>("Objetivo")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("objetivo");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_alta");

                    b.Property<int?>("UsuarioBaja")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_baja");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id")
                        .HasName("pk_socios");

                    b.ToTable("socios", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.MedicionFisica", b =>
                {
                    b.HasOne("GymBro.Domain.Entities.Socio", "Socio")
                        .WithMany("HistorialFisico")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mediciones_fisicas_socios_socio_id");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GymBro.Domain.Entities.SesionEjercicio", b =>
                {
                    b.HasOne("GymBro.Domain.Entities.Ejercicio", "Ejercicio")
                        .WithMany()
                        .HasForeignKey("EjercicioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sesiones_ejercicios_ejercicios_ejercicio_id");

                    b.HasOne("GymBro.Domain.Entities.SesionEntrenamiento", "Sesion")
                        .WithMany("EjerciciosEjecutados")
                        .HasForeignKey("SesionId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sesiones_ejercicios_sesiones_sesion_id");

                    b.Navigation("Ejercicio");

                    b.Navigation("Sesion");
                });

            modelBuilder.Entity("GymBro.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.HasOne("GymBro.Domain.Entities.Socio", null)
                        .WithMany("Sesiones")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_sesiones_socios_socio_id");
                });

            modelBuilder.Entity("GymBro.Domain.Entities.SesionEntrenamiento", b =>
                {
                    b.Navigation("EjerciciosEjecutados");
                });

            modelBuilder.Entity("GymBro.Domain.Entities.Socio", b =>
                {
                    b.Navigation("HistorialFisico");

                    b.Navigation("Sesiones");
                });
#pragma warning restore 612, 618
        }
    }
}
