// <auto-generated />
using System;
using GymBro.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace GymBro.Infrastructure.Migrations
{
    [DbContext(typeof(GymBroDbContext))]
    [Migration("20260819131125_EstandarizacionAuditoriaYSnakeCase")]
    partial class EstandarizacionAuditoriaYSnakeCase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("GymBro.Domain.Entities.Ejercicio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector")
                        .HasColumnName("embedding");

                    b.Property<string>("Equipamiento")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("equipamiento");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("GrupoMuscular")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("grupo_muscular");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_alta");

                    b.Property<int?>("UsuarioBaja")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_baja");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id")
                        .HasName("pk_ejercicios");

                    b.ToTable("ejercicios", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.MedicionFisica", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("AlturaCm")
                        .HasColumnType("numeric")
                        .HasColumnName("altura_cm");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<decimal>("PesoKg")
                        .HasColumnType("numeric")
                        .HasColumnName("peso_kg");

                    b.Property<Guid>("SocioId")
                        .HasColumnType("uuid")
                        .HasColumnName("socio_id");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_alta");

                    b.Property<int?>("UsuarioBaja")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_baja");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id")
                        .HasName("pk_mediciones");

                    b.HasIndex("SocioId")
                        .HasDatabaseName("ix_mediciones_socio_id");

                    b.ToTable("mediciones", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.Socio", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Apellido")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("apellido");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("email");

                    b.Property<DateTime>("FechaAlta")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_alta");

                    b.Property<DateTime?>("FechaBaja")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_baja");

                    b.Property<DateTime?>("FechaModificacion")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fecha_modificacion");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("nombre");

                    b.Property<int>("UsuarioAlta")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_alta");

                    b.Property<int?>("UsuarioBaja")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_baja");

                    b.Property<int?>("UsuarioModificacion")
                        .HasColumnType("integer")
                        .HasColumnName("usuario_modificacion");

                    b.HasKey("Id")
                        .HasName("pk_socios");

                    b.ToTable("socios", (string)null);
                });

            modelBuilder.Entity("GymBro.Domain.Entities.MedicionFisica", b =>
                {
                    b.HasOne("GymBro.Domain.Entities.Socio", "Socio")
                        .WithMany("HistorialFisico")
                        .HasForeignKey("SocioId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_mediciones_socios_socio_id");

                    b.Navigation("Socio");
                });

            modelBuilder.Entity("GymBro.Domain.Entities.Socio", b =>
                {
                    b.Navigation("HistorialFisico");
                });
#pragma warning restore 612, 618
        }
    }
}
